import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./AuthContext";
import Header from "./Header";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 text-gray-900`}>
        <AuthProvider>
          <Header />
          {/* Navigation */}
          <nav className="flex items-center justify-between py-6 px-8 bg-white shadow-md">
            <div className="flex items-center gap-8">
              <Link href="/" className="font-bold text-2xl text-blue-900">CleanCo</Link>
              <Link href="/services" className="text-blue-900 font-semibold hover:text-blue-700">Services</Link>
              {/* Removed Contact Us and Referral links */}
              {/* <Link href="/contact" className="text-blue-900 font-semibold hover:text-blue-700">Contact Us</Link> */}
              {/* <Link href="/referral" className="text-blue-900 font-semibold hover:text-blue-700">Referral</Link> */}
            </div>
          </nav>
          <main className="container mx-auto px-4 py-8 min-h-[70vh]">{children}</main>
          <footer className="bg-gray-900 text-white py-8 mt-8">
            <div className="container mx-auto px-4 flex flex-col md:flex-row justify-between items-center gap-8">
              <div className="mb-4 md:mb-0">
                <div className="font-bold text-xl mb-2">CleanCo</div>
                <div className="text-sm">&copy; 2025 CleanCo. All rights reserved.</div>
              </div>
              <div className="flex flex-col md:flex-row gap-6 items-center">
                <div>
                  <div className="font-semibold mb-2">Quick Links</div>
                  <ul className="text-sm space-y-1">
                    <li><a href="/" className="hover:underline">Home</a></li>
                    <li><a href="/services" className="hover:underline">Services</a></li>
                  </ul>
                </div>
                <div>
                  <div className="font-semibold mb-2">Contact</div>
                  <ul className="text-sm space-y-1">
                    <li>Email: <a href="mailto:info@cleanco.com" className="hover:underline">info@cleanco.com</a></li>
                    <li>Phone: <a href="tel:+1234567890" className="hover:underline">+1 234 567 890</a></li>
                    <li>Address: 123 Clean St, Accra, Ghana</li>
                  </ul>
                </div>
              </div>
            </div>
          </footer>
        </AuthProvider>
      </body>
    </html>
  );
}

