import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider, useAuth } from "./AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 text-gray-900`}>
        <AuthProvider>
          <Header />
          <main className="container mx-auto px-4 py-8 min-h-[70vh]">{children}</main>
          <footer className="bg-gray-900 text-white text-center py-4 mt-8">
            &copy; 2025 CleanCo. All rights reserved.
          </footer>
        </AuthProvider>
      </body>
    </html>
  );
}

function Header() {
  const { user, logout } = useAuth();
  return (
    <header className="bg-blue-900 text-white py-4">
      <nav className="container mx-auto flex justify-between items-center px-4">
        <div className="font-bold text-xl">CleanCo</div>
        <ul className="flex gap-6 items-center">
          <li><a href="/" className="hover:underline">Home</a></li>
          <li><a href="/services" className="hover:underline">Services</a></li>
          <li><a href="/contact" className="hover:underline">Contact</a></li>
          <li><a href="/dashboard" className="hover:underline">Dashboard</a></li>
          <li><a href="/referrals" className="hover:underline">Referrals</a></li>
          <li><a href="/register" className="hover:underline">Register</a></li>
          <li><a href="/login" className="hover:underline">Login</a></li>
          {user && (
            <>
              <li className="ml-4 text-sm">Logged in as <span className="font-semibold">{user.email}</span></li>
              <li><button onClick={logout} className="bg-white text-blue-900 px-3 py-1 rounded font-bold">Logout</button></li>
            </>
          )}
        </ul>
      </nav>
    </header>
  );
}
